package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/palemoky/chinese-poetry-api/internal/database"
	"github.com/palemoky/chinese-poetry-api/internal/graph/generated"
	"github.com/palemoky/chinese-poetry-api/internal/graph/model"
)

// Poems is the resolver for the poems field.
//
// Note: this field has no lang argument and gqlgen resolves child fields with
// the original request context, so the parent query's lang cannot reach here -
// these poems are always simplified. Giving Author.poems its own lang argument
// would fix it, but that is a schema change.
func (r *authorResolver) Poems(ctx context.Context, obj *database.Author, page *int, pageSize *int) (*database.PoemConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	poems, totalCount, err := r.Repo.ListAuthorPoems(obj.ID, pag.PageSize, pag.Offset)
	if err != nil {
		return nil, err
	}

	return buildPoemConnection(poems, pag, totalCount), nil
}

// PoemCount is the resolver for the poemCount field.
//
// Counts here and on Dynasty/PoetryType use the default (simplified) tables.
// Like Author.poems above they cannot see the query's lang, but unlike it that
// is harmless: the variants hold the same corpus converted, so the counts match.
func (r *authorResolver) PoemCount(ctx context.Context, obj *database.Author) (int, error) {
	return r.Repo.CountPoemsByAuthor(obj.ID)
}

// Node is the resolver for the node field.
func (r *authorEdgeResolver) Node(ctx context.Context, obj *database.AuthorEdge) (*database.Author, error) {
	return &obj.Node.Author, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *dynastyResolver) PoemCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	return r.Repo.CountPoemsByDynasty(obj.ID)
}

// AuthorCount is the resolver for the authorCount field.
func (r *dynastyResolver) AuthorCount(ctx context.Context, obj *database.Dynasty) (int, error) {
	return r.Repo.CountAuthorsByDynasty(obj.ID)
}

// Content is the resolver for the content field.
func (r *poemResolver) Content(ctx context.Context, obj *database.Poem) ([]string, error) {
	var content []string
	if err := json.Unmarshal(obj.Content, &content); err != nil {
		return nil, err
	}
	return content, nil
}

// PoemCount is the resolver for the poemCount field.
func (r *poetryTypeResolver) PoemCount(ctx context.Context, obj *database.PoetryType) (int, error) {
	return r.Repo.CountPoemsByType(obj.ID)
}

// Poem is the resolver for the poem field.
func (r *queryResolver) Poem(ctx context.Context, id string, lang *database.Lang) (*database.Poem, error) {
	repo := r.Repo.WithLang(parseLang(lang))

	poem, err := repo.GetPoemByID(id)
	if err != nil {
		return nil, err
	}
	return poem, nil
}

// Poems is the resolver for the poems field.
func (r *queryResolver) Poems(ctx context.Context, lang *database.Lang, page *int, pageSize *int, dynastyID *string, authorID *string, typeID *string) (*database.PoemConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	// Parse filter IDs
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}
	authorIDInt, err := parseOptionalID(authorID)
	if err != nil {
		return nil, err
	}
	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}

	// The GraphQL schema exposes a single typeID; the repository takes a slice
	// because the REST endpoint accepts repeated type_id params.
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	repo := r.Repo.WithLang(parseLang(lang))
	poems, totalCount, err := repo.ListPoemsWithFilter(pag.PageSize, pag.Offset, dynastyIDInt, authorIDInt, typeIDs)
	if err != nil {
		return nil, err
	}

	return buildPoemConnection(poems, pag, totalCount), nil
}

// SearchPoems is the resolver for the searchPoems field.
func (r *queryResolver) SearchPoems(ctx context.Context, query string, lang *database.Lang, searchType *model.SearchType, page *int, pageSize *int) (*database.PoemConnection, error) {
	// Use the shared helper rather than reading the arguments directly, which
	// is what let this resolver bypass the pageSize cap the others enforce.
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	// Map GraphQL search type to repository search type
	st := "all"
	if searchType != nil {
		switch *searchType {
		case model.SearchTypeTitle:
			st = "title"
		case model.SearchTypeContent:
			st = "content"
		case model.SearchTypeAuthor:
			st = "author"
		}
	}

	// Use repository's SearchPoems with language context
	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	poems, total, err := repo.SearchPoems(query, st, pag.Page, pag.PageSize)
	if err != nil {
		return nil, err
	}

	// Build the connection with the shared helper rather than by hand. The
	// hand-rolled version numbered cursors from 0 within each page, so page 2's
	// first edge carried the same cursor as page 1's, and it left startCursor
	// and endCursor unset while every other connection populates them.
	return buildPoemConnection(poems, pag, int(total)), nil
}

// RandomPoem is the resolver for the randomPoem field.
func (r *queryResolver) RandomPoem(ctx context.Context, lang *database.Lang, dynastyID *string, typeID *string) (*database.Poem, error) {
	// Parse filter IDs. A malformed id is an error, not a filter to drop: a
	// discarded filter used to widen the query to the whole corpus and return
	// an unrelated poem, which is indistinguishable from a working request.
	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	typeIDInt, err := parseOptionalID(typeID)
	if err != nil {
		return nil, err
	}
	var typeIDs []int64
	if typeIDInt != nil {
		typeIDs = []int64{*typeIDInt}
	}

	// Use repository's GetRandomPoem with language context (same as REST)
	langVal := parseLang(lang)
	repo := r.Repo.WithLang(langVal)
	return repo.GetRandomPoem(dynastyIDInt, nil, typeIDs)
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string, lang *database.Lang) (*database.Author, error) {
	authorID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}

	// Use Repository method which handles dynamic table names
	return r.Repo.WithLang(parseLang(lang)).GetAuthorByID(authorID)
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context, lang *database.Lang, page *int, pageSize *int, dynastyID *string) (*database.AuthorConnection, error) {
	pag, err := parsePagination(page, pageSize)
	if err != nil {
		return nil, err
	}

	dynastyIDInt, err := parseOptionalID(dynastyID)
	if err != nil {
		return nil, err
	}

	repo := r.Repo.WithLang(parseLang(lang))
	authors, totalCount, err := repo.ListAuthorsWithFilter(pag.PageSize, pag.Offset, dynastyIDInt)
	if err != nil {
		return nil, err
	}

	return buildAuthorConnection(authors, pag, totalCount), nil
}

// Dynasties is the resolver for the dynasties field.
func (r *queryResolver) Dynasties(ctx context.Context, lang *database.Lang) ([]*database.Dynasty, error) {
	var dynasties []*database.Dynasty
	langVal := parseLang(lang)
	err := r.DB.Table(database.DynastiesTable(langVal)).Order("id").Find(&dynasties).Error
	if err != nil {
		return nil, err
	}
	return dynasties, nil
}

// PoemTypes is the resolver for the poemTypes field.
func (r *queryResolver) PoemTypes(ctx context.Context, lang *database.Lang) ([]*database.PoetryType, error) {
	var types []*database.PoetryType
	langVal := parseLang(lang)
	err := r.DB.Table(database.PoetryTypesTable(langVal)).Order("id").Find(&types).Error
	if err != nil {
		return nil, err
	}
	return types, nil
}

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context, lang *database.Lang) (*database.Statistics, error) {
	return r.Repo.GetStatistics()
}

// PoemsByDynasty is the resolver for the poemsByDynasty field.
func (r *statisticsResolver) PoemsByDynasty(ctx context.Context, obj *database.Statistics) ([]*model.DynastyStats, error) {
	stats := make([]*model.DynastyStats, len(obj.PoemsByDynasty))
	for i, ds := range obj.PoemsByDynasty {
		stats[i] = &model.DynastyStats{
			Dynasty: &ds.Dynasty,
			Count:   ds.PoemCount,
		}
	}
	return stats, nil
}

// PoemsByType is the resolver for the poemsByType field.
func (r *statisticsResolver) PoemsByType(ctx context.Context, obj *database.Statistics) ([]*model.TypeStats, error) {
	stats := make([]*model.TypeStats, len(obj.PoemsByType))
	for i, ts := range obj.PoemsByType {
		stats[i] = &model.TypeStats{
			Type:  &ts.PoetryType,
			Count: ts.PoemCount,
		}
	}
	return stats, nil
}

// Author returns generated.AuthorResolver implementation.
func (r *Resolver) Author() generated.AuthorResolver { return &authorResolver{r} }

// AuthorEdge returns generated.AuthorEdgeResolver implementation.
func (r *Resolver) AuthorEdge() generated.AuthorEdgeResolver { return &authorEdgeResolver{r} }

// Dynasty returns generated.DynastyResolver implementation.
func (r *Resolver) Dynasty() generated.DynastyResolver { return &dynastyResolver{r} }

// Poem returns generated.PoemResolver implementation.
func (r *Resolver) Poem() generated.PoemResolver { return &poemResolver{r} }

// PoetryType returns generated.PoetryTypeResolver implementation.
func (r *Resolver) PoetryType() generated.PoetryTypeResolver { return &poetryTypeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Statistics returns generated.StatisticsResolver implementation.
func (r *Resolver) Statistics() generated.StatisticsResolver { return &statisticsResolver{r} }

type authorResolver struct{ *Resolver }
type authorEdgeResolver struct{ *Resolver }
type dynastyResolver struct{ *Resolver }
type poemResolver struct{ *Resolver }
type poetryTypeResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type statisticsResolver struct{ *Resolver }
